### ISSUE TITLE
`bbin ls` fails if the `bbin` bin has a 0-length file

### ISSUE THREAD

**Issue by jdjohnston** [babashka/bbin#88] opened 2024-08-17 17:56 UTC
Why would the bin have a 0-length file? I don't know about others, but I use 0-length files, .e.g. `.notar`,  as flags in my dirs.

It's an easy fix. Add something like `(> (fs/size %) 0)` to the file filter in `load-scripts` (currently line 1510 in `bbin`). The change worked fine for me on a local copy of `bbin`.

Thanks for this cool util!

**Comment by borkdude** [comment] 2024-08-17 18:44
What's the error your getting, just out of curiosity? Can you paste a stack trace?

**Comment by jdjohnston** [comment] 2024-08-19 01:28
@borkdude my laptop is currently offline,  but I can provide a verbal stack trace. 

`str/split-lines` in `parse-script` errs with a `NullPointerException` because  `read-header` returns a `nil` for a 0-length file. `read-header` returns a `nil` because `.read` returns `-1`, which isn't a `nat-int?`.

Arguably, a cleaner fix might be to change `read-header` from `(when (nat-int? n) ...)` to `(if (nat-int? n) ... "")`, so that it always returns a string, even for a 0-length file.

**Comment by borkdude** [comment] 2024-08-19 07:57
@jdjohnston Nice! Since you analyzed the root cause, perhaps you're willing to put a PR together? If not, I'll get it sooner or later!

**Comment by borkdude** [comment] 2024-08-23 18:07
I took a look at this issue and don't see why read-header has the `(when (nat-int? n) ..)` condition. You can create a string like this: `(String. (byte-array (range 1000)) 0 0)` which is just an empty string. Can we remove the condition @rads?

**Comment by rads** [comment] 2024-08-23 18:30
That sounds good to me. 👍

**Comment by jdjohnston** [comment] 2024-08-23 20:56
Don't forget, `.read` returns `-1` when the file is 0-length. (Conflating
0-length with EOF?)

**Comment by jdjohnston** [comment] 2024-08-26 23:24
How about `(String. buffer 0 (max 0 n))`  ?

`n` will be one of three values:
- `-1` => 0-length file
-  size of `buffer` => file size `>=` `buffer` size
-  some value `<` `buffer` size => `0` `<` file size `<` `buffer` size

**Comment by borkdude** [comment] 2024-08-31 07:32
Sorry, I got a little overwhelmed with other issues. Feel free to submit a PR if you'd like

**Comment by borkdude** [comment] 2024-09-05 15:32
@jdjohnston Perhaps you're able to test now that I've merged this

**Closed** 2024-09-05 15:31 UTC
Labels: bug

**Comment by jdjohnston** [comment] 2024-09-08 17:01
@borkdude Works for me _after_ I remembeed to `bb gen-script`. Your fix is different than either of _my_ suggestions :), but it works fine.

I suppose `gen-script` will be executed for the next release. Am I understanding the workflow correctly?

BTW, I _do_ understand it is better to fix a root-cause than to "band-aid" a symptom. Thanks for the reminder. Next time, feel free to be more blunt. It won't hurt my feelings. :)

**Comment by borkdude** [comment] 2024-09-08 17:33
Returning an empty string was one of your suggestions right?

**Comment by borkdude** [comment] 2024-09-08 17:50
Published as 0.2.4

**Comment by jdjohnston** [comment] 2024-09-08 18:20
@borkdude I was largely joking. Absolutely no criticism intended. There are probably even more ways to return an empty string. If I truly wanted it done in a certain way, I should have made more effort to generate a PR.

It _works_. That's the important part.
